### ISSUE TITLE
Error when Start.py is running

### ISSUE THREAD

**Issue by pritudev** [ggeop/Python-ai-assistant#117]
When the start.py file runs i get this error

```bash
\Traceback (most recent call last):
  File "c:\Users\pritg\Downloads\Python-ai-assistant-develop\Python-ai-assistant-develop\src\jarvis\start.py", line 3, in <module>
    from jarvis import settings
  File "c:\Users\pritg\Downloads\Python-ai-assistant-develop\Python-ai-assistant-develop\src\jarvis\jarvis\__init__.py", line 26, in 
<module>
    configure_MongoDB(db, settings)
  File "c:\Users\pritg\Downloads\Python-ai-assistant-develop\Python-ai-assistant-develop\src\jarvis\jarvis\utils\startup.py", line 77, in configure_MongoDB
    from jarvis.skills.registry import CONTROL_SKILLS, ENABLED_BASIC_SKILLS
  File "c:\Users\pritg\Downloads\Python-ai-assistant-develop\Python-ai-assistant-develop\src\jarvis\jarvis\skills\registry.py", line 
20, in <module>
    from jarvis.skills.collection.configuration import ConfigurationSkills
  File "c:\Users\pritg\Downloads\Python-ai-assistant-develop\Python-ai-assistant-develop\src\jarvis\jarvis\skills\collection\configuration.py", line 12, in <module>
    input_mode = db.get_documents(collection='general_settings')[0]['input_mode']
TypeError: 'NoneType' object is not subscriptable
```

Please help me to fix this error

**Comment by 11Tuvork28** [comment]
Looks like a Mongodb error but as you use Windows I can't help you as this project is not designed to work on windows.

**Comment by pritudev** [comment]
Okay then i'll install ubuntu then come back later...

**Comment by pritudev** [comment]
I am on Ubuntu now!

**Comment by pritudev** [comment]
> Looks like a Mongodb error but as you use Windows I can't help you as this project is not designed to work on windows.

Tell me what to do?

**Comment by pritudev** [comment]
```bash
$ bash run_jarvis.sh 
run_jarvis.sh: line 10: ./jarvis_virtualenv/bin/python: No such file or directory
```
