### ISSUE TITLE
pymongo not installing properly

### ISSUE THREAD

**Issue by apensotti** [ggeop/Python-ai-assistant#150]
Failed to start mongodb.service: Unit mongodb.service not found.
Traceback (most recent call last):
  File "/home/alexp/Python-ai-assistant/./src/jarvis/start.py", line 23, in <module>
    from jarvis import settings
  File "/home/alexp/Python-ai-assistant/src/jarvis/jarvis/__init__.py", line 27, in <module>
    from jarvis.utils.mongoDB import db
  File "/home/alexp/Python-ai-assistant/src/jarvis/jarvis/utils/mongoDB.py", line 24, in <module>
    from pymongo import MongoClient, DESCENDING
ModuleNotFoundError: No module named 'pymongo'
Failed to stop mongodb.service: Unit mongodb.service not loaded.

Not sure if it's a problem with the setup.sh file, or with my instance of python. I pip installed pymongo, ran the setup.sh file, and got this error after running the run_jarvis.sh file.

**Comment by apensotti** [comment]
There seem to be a lot of missing dependencies

**Comment by luandro** [comment]
I'm having a similar issue where the dependencies from 'requirements.txt' isn't being recognized, although they are within the `./jarvis_virtualenv/lib` and `lib64` folders. @ggeop Any tips on why `ModuleNotFoundError` is thrown for every module?
