### ISSUE TITLE
I am trying to run this via a network MongoDB by changing the host (as I already have it setup on another box) but I get nonetype object errors

### ISSUE THREAD

**Issue by decrecondiz** [ggeop/Python-ai-assistant#71]
Traceback attached below:

Traceback (most recent call last):
  File "start.py", line 23, in <module>
    from jarvis import settings
  File "G:\Desktop\Python-ai-assistant-master\src\jarvis\jarvis\__init__.py", line 46, in <module>
    configure_MongoDB(db, settings)
  File "G:\Desktop\Python-ai-assistant-master\src\jarvis\jarvis\utils\startup.py", line 97, in configure_MongoDB
    from jarvis.skills.registry import CONTROL_SKILLS, ENABLED_BASIC_SKILLS
  File "G:\Desktop\Python-ai-assistant-master\src\jarvis\jarvis\skills\registry.py", line 40, in <module>
    from jarvis.skills.collection.configuration import ConfigurationSkills
  File "G:\Desktop\Python-ai-assistant-master\src\jarvis\jarvis\skills\collection\configuration.py", line 32, in <module>
    input_mode = db.get_documents(collection='general_settings')[0]['input_mode']
TypeError: 'NoneType' object is not subscriptable

I have checked the configuration.py and can see the below so I would assume its either the key or the limit parameters?:
def get_documents(self, collection, key=None, limit=None):

Any help is greatly appreciated

**Comment by ggeop** [comment]
Hi @decrecondiz,

Normally this MongoDB call (get_documents) it works, I suppose that the error is related with the MongoDB server. The keys 'key' and 'limit' are correct, are not mandatory fields. 

You mentioned that you have changed the host, maybe this is the problem. Can you describe me what changes have you done for different host, and also can you check the connectivity with MongoDB server? I have tested it with local MongoDB, with remote DB maybe you will face connectivity problems.
