### ISSUE TITLE
Failed to stop mongod.service: Unit mongod.service not loaded.

### ISSUE THREAD

**Issue by Kaustubh1919** [ggeop/Python-ai-assistant#73]
Failed to start mongod.service: Unit mongod.service not found.
Traceback (most recent call last):
  File "./src/jarvis/start.py", line 23, in <module>
    from jarvis import settings
  File "/home/blackhat/Python-ai-assistant-master/src/jarvis/jarvis/__init__.py", line 46, in <module>
    configure_MongoDB(db, settings)
  File "/home/blackhat/Python-ai-assistant-master/src/jarvis/jarvis/utils/startup.py", line 97, in configure_MongoDB
    from jarvis.skills.registry import CONTROL_SKILLS, ENABLED_BASIC_SKILLS
  File "/home/blackhat/Python-ai-assistant-master/src/jarvis/jarvis/skills/registry.py", line 38, in <module>
    from jarvis.skills.collection.math import MathSkills
  File "/home/blackhat/Python-ai-assistant-master/src/jarvis/jarvis/skills/collection/math.py", line 23, in <module>
    from word2number import w2n
  File "/home/blackhat/Python-ai-assistant-master/jarvis_virtualenv/lib/python3.7/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named word2number
Failed to stop mongod.service: Unit mongod.service not loaded.

**Comment by ggeop** [comment]
Hi @Kaustubh1919,

I add the missing dependency in the requirements.txt. You can pull the the fix and run the setup.sh again or enable the jarvis_virtualenv and install only the missing dependency (pip install word2number==1.1)
